# action masking
IMPOSSIBLE_PENALTY = -1e9

# DQN related
EPSILON_P = 0.01

# log related
LOG_EPSILON = 1e-9

# FFXIV combat system related
UNIT_TIME_PER_ACTION_MILLISECOND = 100
DO_NOTHING_ACTION_ID = 0
DEFAULT_DELAY_MILLISECOND = 700
MAX_POTENCY = 2000
COMBO_TIMER_MAX_MILLISECOND = 30000
MAX_REGEN_TIME_MILLISECOND = 30000
